### PR TITLE
Bump version and use newer arbitrary-int version

### PR DESCRIPTION
**Pull request by danlehmann**

### CODE REVIEW

**Review by hecatia-elegua — APPROVED** [review]
Propagating const nightly stuff can be done later

**Comment by danlehmann** [comment]
> Propagating const nightly stuff can be done later

Ugh I hadn't thought of that. If the user opts-in to the nightly features in arbitrary-int but uses vanilla bitbybit, would they get an incompatible arbitrary-int instance?

**Comment by danlehmann** [comment]
Actually no, that shouldn't be the case as bitbybit doesn't bring any code by itself. It's just macros so the arbitrary-int instances are all created by the user.

So I think we don't need to pass this flag through, unless I am missing something?

**Comment by hecatia-elegua** [comment]
Oh right we don't depend on those, it's already const here, oops

**Comment by danlehmann** [comment]
Yes const the whole reason I went for new_with_raw_value() and functions like that (instead of From<>), as they can easily be made const

**Pull request merged**
